GithubExplorer/Models/GithubAPI.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;

namespace GithubExplorer.Models
{
    public class GithubAPI
    {
        private static readonly string MainURL = @"https://api.github.com/search/repositories?q=";

        public static async Task<List<Repository>> GetRepositories(string query)
        {
            using (HttpClient client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("User-Agent", "request");
                using (HttpResponseMessage response = await client.GetAsync(MainURL + query))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        string JsonResult = await response.Content.ReadAsStringAsync();
                        return Json.Decode<GithubAPIResponse>(JsonResult).items;
                    }
                    return new List<Repository>();
                }

            }

        }

    }
}

GithubExplorer/Models/GithubAPIResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GithubExplorer.Models
{
    public class GithubAPIResponse
    {
        public int total_count;
        public List<Repository> items;
    }
}

GithubExplorer/Models/Owner.cs
namespace GithubExplorer.Models
{
    public class Owner
    {
        public string login;
        public string avatar_url;
        public string html_url;
    }
}

GithubExplorer/Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GithubExplorer.Models
{
    public class Repository
    {
        public int id;
        public string name;
        public string html_url;
        public Owner owner;

    }
}

GithubExplorer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GithubExplorer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

GithubExplorer/Controllers/RepositoryController.cs
using GithubExplorer.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace GithubExplorer.Controllers
{
    public class RepositoryController : Controller
    {

        public async Task<ActionResult> Index(string query)
        {
            List<Repository> result = await GithubAPI.GetRepositories(query);
            Dictionary<int, Repository> resultDictionary = new Dictionary<int, Repository>(result.Count);
            result.ForEach(r => resultDictionary.Add(r.id, r));
            return View(resultDictionary);
        }

        public ActionResult Favorites(string jsonItem, string type)
        {
            Repository item = null;
            Dictionary<int, Repository> repositoryList = (Dictionary<int, Repository>)Session["favorites"];
            if (repositoryList == null)
            {
                repositoryList = new Dictionary<int, Repository>();
                Session["favorites"] = repositoryList;
            }
            if (jsonItem != null)
            {
                item = System.Web.Helpers.Json.Decode<Repository>(jsonItem);
            }
            if (type == "add")
            {
                AddToFavorites(item, repositoryList);
            }
            if (type == "remove")
            {
                RemoveFromFavorites(item, repositoryList);
            }
            return View("Favorites", repositoryList);
        }

        private void RemoveFromFavorites(Repository item, Dictionary<int, Repository> repositoryList)
        {
            repositoryList.Remove(item.id);
        }

        private void AddToFavorites(Repository item, Dictionary<int, Repository> repositoryList)
        {
            if (item != null && item.id != 0 && !repositoryList.ContainsKey(item.id))
            {
                repositoryList.Add(item.id, item);
            }
        }


        [ChildActionOnly]
        public ActionResult Gallery(Dictionary<int,Repository> repositoryList)
        {
            return PartialView(repositoryList);
        }

    }
}

GithubExplorer/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron mt-30">
    <h1>GitHub Explorer</h1>
    <p class="lead">
        GitHub Explorer is a simple GitHub Repository search tool<br />
        Come close to the open-source
    </p>
    <p><a href="@Url.Action("Index","Repository")" class="btn btn-primary btn-lg mt-15">Start now &raquo;</a></p>
</div>

GithubExplorer/Views/Repository/Favorites.cshtml
@model Dictionary<int,GithubExplorer.Models.Repository>

@{
    ViewBag.Title = "Favorites";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>My Favorites</h2>

@{Html.RenderPartial("Gallery", Model); }

GithubExplorer/Views/Repository/Gallery.cshtml
@model Dictionary<int, GithubExplorer.Models.Repository>
@{ Dictionary<int, GithubExplorer.Models.Repository> favorites = (Dictionary<int, GithubExplorer.Models.Repository>)Session["favorites"]; }

@if (Model.Count == 0)
{
    <div class="container mt-15">
        <div class="row text-center">
            <div class="col-10 m-auto">
                <i>There are no repositories to display</i>
            </div>
        </div>
    </div>
}
<div class="row text-center">
    @if (Model.Count > 0 && Model != null)
    {
        foreach (GithubExplorer.Models.Repository item in Model.Values)
        {
            <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                <div class="card mt-15">
                    <img src="@item.owner.avatar_url" class="card-img-top">
                    <p class="card-text d-inline">
                        <a href="@item.html_url">@item.name</a><br>
                        by: <a href="@item.owner.html_url">@item.owner.login</a>
                    </p>
                    @if (favorites == null || (favorites != null && !favorites.ContainsKey(item.id)))
                    {
                        @Html.ActionLink("Add to Favorites",
        "Favorites",
        "Repository",
        new { jsonItem = Json.Encode(item), type="add" },
        new { @class = "btn btn-primary form-control mt-5" })
                    }
                    @if (favorites != null && favorites.ContainsKey(item.id))
                    {
                        @Html.ActionLink("Remove from Favorites",
        "Favorites",
        "Repository",
        new { jsonItem = Json.Encode(item), type="remove" },
        new { @class = "btn btn-danger form-control mt-5" })
                    }
                </div>
            </div>
        }
    }
</div>

GithubExplorer/Views/Repository/Index.cshtml
@model Dictionary<int,GithubExplorer.Models.Repository>
@{
    ViewBag.Title = "Repositories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container search-bar mt-15">
    <div class="row text-center">
        <div class="col-12">
            @using (Html.BeginForm())
            {
                <input name="query" type="text" class="form-control d-inline" placeholder="Search Repository...">
                <button class="btn btn-primary d-inline" type="submit">Search</button>
            }
        </div>
    </div>
</div>

@{ Html.RenderPartial("Gallery", Model); }

GithubExplorer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GitHub Explorer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Github Explorer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Search", "Index", "Repository")</li>
                    <li>@Html.ActionLink("Favorites", "Favorites", "Repository")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>